export const ADD_PRODUCT_BASKET='ADD_PRODUCT_BASKET';
export const GET_NUMBERS_BASKET=' GET_NUMBERS_BASKET';
export const INCREASE_QUANT='INCREASE_QUANT';
export const DECREASE_QUANT='DECREASE_QUANT';
